version: "3.9"
services:
  frontend:
    image: felixgi1516/geosoft2_frontend:latest
    depends_on:
      - processManager
      - database
      - ndvi_0
      - sst_0
    ports:
      - 8080:8080
    environment:
      - DOCKER=True
    volumes:
      - data-volume:/data
  processManager:
    image: felixgi1516/geosoft2_jobmanagement:latest
    environment:
      - DOCKER=True
      - ndvi=ndvi_0
      - mean_sst=sst_0
      - load_collection=database
    depends_on:
      - database
      - ndvi_0
      - sst_0
    ports:
      - 80
    volumes:
      - data-volume:/data
  database:
    image: felixgi1516/geosoft2_dataserver:latest
    environment:
      - DOCKER=True
    ports:
      - 80
    volumes:
      - data-volume:/data
  ndvi_0:
    image: felixgi1516/geosoft2_ndvi_process:latest
    environment:
      - DOCKER=True
    ports:
      - 80
    volumes:
      - data-volume:/data
  sst_0:
    image: felixgi1516/geosoft2_sst_process:latest
    environment:
      - DOCKER=True
    ports:
      - 80
    volumes:
      - data-volume:/data
volumes:
  data-volume:
